#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from yacc.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "yacc.y"

#include<stdio.h>
#include<math.h>
#include<stdlib.h>
extern int yylex();
extern int yyparse();
extern FILE *yyin;


#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	T_LT	258
#define	T_GT	259
#define	T_LE	260
#define	T_GE	261
#define	T_EQUAL	262
#define	T_UNEQUAL	263
#define	T_PLUS	264
#define	T_MINUS	265
#define	T_OR	266
#define	T_MUL	267
#define	T_DIV	268
#define	T_MOD	269
#define	T_AND	270
#define	T_NOT	271
#define	T_PROGRAM	272
#define	T_VAR	273
#define	T_INT	274
#define	T_REAL	275
#define	T_ID	276
#define	T_STRING	277
#define	T_BEGIN	278
#define	T_END	279
#define	T_READ	280
#define	T_WRITE	281
#define	T_IF	282
#define	T_THEN	283
#define	T_ELSE	284
#define	T_WHILE	285
#define	T_DO	286
#define	T_TO	287
#define	T_DOWNTO	288
#define	T_FOR	289
#define	T_ASSIGN	290
#define	T_LB	291
#define	T_RB	292
#define	T_LP	293
#define	T_RP	294
#define	T_SEMI	295
#define	T_DOT	296
#define	T_DOTDOT	297
#define	T_COMMA	298
#define	T_COLON	299
#define	T_INTEGER_TYPE	300
#define	T_BOOLEAN_TYPE	301
#define	T_CHAR_TYPE	302
#define	T_REAL_TYPE	303
#define	T_ARRAY	304
#define	T_OF	305


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int T_LT;
static const int T_GT;
static const int T_LE;
static const int T_GE;
static const int T_EQUAL;
static const int T_UNEQUAL;
static const int T_PLUS;
static const int T_MINUS;
static const int T_OR;
static const int T_MUL;
static const int T_DIV;
static const int T_MOD;
static const int T_AND;
static const int T_NOT;
static const int T_PROGRAM;
static const int T_VAR;
static const int T_INT;
static const int T_REAL;
static const int T_ID;
static const int T_STRING;
static const int T_BEGIN;
static const int T_END;
static const int T_READ;
static const int T_WRITE;
static const int T_IF;
static const int T_THEN;
static const int T_ELSE;
static const int T_WHILE;
static const int T_DO;
static const int T_TO;
static const int T_DOWNTO;
static const int T_FOR;
static const int T_ASSIGN;
static const int T_LB;
static const int T_RB;
static const int T_LP;
static const int T_RP;
static const int T_SEMI;
static const int T_DOT;
static const int T_DOTDOT;
static const int T_COMMA;
static const int T_COLON;
static const int T_INTEGER_TYPE;
static const int T_BOOLEAN_TYPE;
static const int T_CHAR_TYPE;
static const int T_REAL_TYPE;
static const int T_ARRAY;
static const int T_OF;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,T_LT=258
	,T_GT=259
	,T_LE=260
	,T_GE=261
	,T_EQUAL=262
	,T_UNEQUAL=263
	,T_PLUS=264
	,T_MINUS=265
	,T_OR=266
	,T_MUL=267
	,T_DIV=268
	,T_MOD=269
	,T_AND=270
	,T_NOT=271
	,T_PROGRAM=272
	,T_VAR=273
	,T_INT=274
	,T_REAL=275
	,T_ID=276
	,T_STRING=277
	,T_BEGIN=278
	,T_END=279
	,T_READ=280
	,T_WRITE=281
	,T_IF=282
	,T_THEN=283
	,T_ELSE=284
	,T_WHILE=285
	,T_DO=286
	,T_TO=287
	,T_DOWNTO=288
	,T_FOR=289
	,T_ASSIGN=290
	,T_LB=291
	,T_RB=292
	,T_LP=293
	,T_RP=294
	,T_SEMI=295
	,T_DOT=296
	,T_DOTDOT=297
	,T_COMMA=298
	,T_COLON=299
	,T_INTEGER_TYPE=300
	,T_BOOLEAN_TYPE=301
	,T_CHAR_TYPE=302
	,T_REAL_TYPE=303
	,T_ARRAY=304
	,T_OF=305


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::T_LT=258;
const int YY_parse_CLASS::T_GT=259;
const int YY_parse_CLASS::T_LE=260;
const int YY_parse_CLASS::T_GE=261;
const int YY_parse_CLASS::T_EQUAL=262;
const int YY_parse_CLASS::T_UNEQUAL=263;
const int YY_parse_CLASS::T_PLUS=264;
const int YY_parse_CLASS::T_MINUS=265;
const int YY_parse_CLASS::T_OR=266;
const int YY_parse_CLASS::T_MUL=267;
const int YY_parse_CLASS::T_DIV=268;
const int YY_parse_CLASS::T_MOD=269;
const int YY_parse_CLASS::T_AND=270;
const int YY_parse_CLASS::T_NOT=271;
const int YY_parse_CLASS::T_PROGRAM=272;
const int YY_parse_CLASS::T_VAR=273;
const int YY_parse_CLASS::T_INT=274;
const int YY_parse_CLASS::T_REAL=275;
const int YY_parse_CLASS::T_ID=276;
const int YY_parse_CLASS::T_STRING=277;
const int YY_parse_CLASS::T_BEGIN=278;
const int YY_parse_CLASS::T_END=279;
const int YY_parse_CLASS::T_READ=280;
const int YY_parse_CLASS::T_WRITE=281;
const int YY_parse_CLASS::T_IF=282;
const int YY_parse_CLASS::T_THEN=283;
const int YY_parse_CLASS::T_ELSE=284;
const int YY_parse_CLASS::T_WHILE=285;
const int YY_parse_CLASS::T_DO=286;
const int YY_parse_CLASS::T_TO=287;
const int YY_parse_CLASS::T_DOWNTO=288;
const int YY_parse_CLASS::T_FOR=289;
const int YY_parse_CLASS::T_ASSIGN=290;
const int YY_parse_CLASS::T_LB=291;
const int YY_parse_CLASS::T_RB=292;
const int YY_parse_CLASS::T_LP=293;
const int YY_parse_CLASS::T_RP=294;
const int YY_parse_CLASS::T_SEMI=295;
const int YY_parse_CLASS::T_DOT=296;
const int YY_parse_CLASS::T_DOTDOT=297;
const int YY_parse_CLASS::T_COMMA=298;
const int YY_parse_CLASS::T_COLON=299;
const int YY_parse_CLASS::T_INTEGER_TYPE=300;
const int YY_parse_CLASS::T_BOOLEAN_TYPE=301;
const int YY_parse_CLASS::T_CHAR_TYPE=302;
const int YY_parse_CLASS::T_REAL_TYPE=303;
const int YY_parse_CLASS::T_ARRAY=304;
const int YY_parse_CLASS::T_OF=305;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		164
#define	YYFLAG		-32768
#define	YYNTBASE	51

#define YYTRANSLATE(x) ((unsigned)(x) <= 305 ? yytranslate[x] : 84)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     7,    10,    11,    14,    16,    21,    25,    27,    29,
    31,    33,    35,    37,    39,    46,    50,    52,    55,    59,
    63,    66,    68,    70,    72,    74,    76,    78,    81,    85,
    89,    93,    95,   100,   102,   104,   108,   110,   114,   117,
   121,   125,   129,   133,   137,   142,   146,   151,   158,   163,
   172,   174,   176,   178,   181,   186,   190,   194,   196,   200,
   204,   208,   212,   216,   220,   222,   226,   228,   232,   236,
   240,   244,   248,   251,   254,   256,   258,   260,   262,   264,
   266
};

static const short yyrhs[] = {    17,
    21,    40,    52,    61,    41,     0,    18,    53,     0,     0,
    53,    54,     0,    54,     0,    55,    44,    56,    40,     0,
    55,    43,    21,     0,    21,     0,    57,     0,    58,     0,
    45,     0,    46,     0,    47,     0,    48,     0,    49,    36,
    59,    37,    50,    57,     0,    60,    42,    60,     0,    82,
     0,    10,    82,     0,    23,    62,    24,     0,    63,    40,
    62,     0,    63,    40,     0,    64,     0,    67,     0,    69,
     0,    72,     0,    73,     0,    74,     0,    26,    65,     0,
    38,    22,    39,     0,    38,    66,    39,     0,    21,    43,
    66,     0,    21,     0,    25,    38,    68,    39,     0,    21,
     0,    71,     0,    21,    35,    70,     0,    81,     0,    38,
    70,    39,     0,    10,    70,     0,    70,     9,    70,     0,
    70,    10,    70,     0,    70,    12,    70,     0,    70,    13,
    70,     0,    70,    14,    70,     0,    21,    36,    81,    37,
     0,    23,    62,    24,     0,    27,    75,    28,    72,     0,
    27,    75,    28,    72,    29,    72,     0,    30,    75,    31,
    72,     0,    34,    21,    35,    79,    83,    79,    31,    72,
     0,    76,     0,    78,     0,    77,     0,    16,    76,     0,
    16,    38,    76,    39,     0,    76,    15,    76,     0,    76,
    11,    76,     0,    21,     0,    79,     7,    79,     0,    79,
     8,    79,     0,    79,     3,    79,     0,    79,     4,    79,
     0,    79,     5,    79,     0,    79,     6,    79,     0,    81,
     0,    38,    79,    39,     0,    80,     0,    79,     9,    79,
     0,    79,    10,    79,     0,    79,    12,    79,     0,    79,
    13,    79,     0,    79,    14,    79,     0,    16,    76,     0,
    10,    79,     0,    21,     0,    82,     0,    71,     0,    19,
     0,    20,     0,    32,     0,    33,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    31,    34,    35,    38,    39,    42,    45,    46,    49,    50,
    53,    54,    55,    56,    59,    62,    65,    65,    68,    71,
    72,    75,    76,    77,    78,    79,    80,    83,    86,    87,
    90,    91,    94,    97,    98,   101,   104,   105,   106,   107,
   108,   109,   110,   111,   113,   117,   120,   121,   124,   125,
   128,   129,   132,   133,   134,   135,   136,   139,   141,   142,
   143,   144,   145,   146,   149,   150,   151,   152,   153,   154,
   155,   156,   159,   160,   163,   164,   165,   168,   169,   172,
   173
};

static const char * const yytname[] = {   "$","error","$illegal.","T_LT","T_GT",
"T_LE","T_GE","T_EQUAL","T_UNEQUAL","T_PLUS","T_MINUS","T_OR","T_MUL","T_DIV",
"T_MOD","T_AND","T_NOT","T_PROGRAM","T_VAR","T_INT","T_REAL","T_ID","T_STRING",
"T_BEGIN","T_END","T_READ","T_WRITE","T_IF","T_THEN","T_ELSE","T_WHILE","T_DO",
"T_TO","T_DOWNTO","T_FOR","T_ASSIGN","T_LB","T_RB","T_LP","T_RP","T_SEMI","T_DOT",
"T_DOTDOT","T_COMMA","T_COLON","T_INTEGER_TYPE","T_BOOLEAN_TYPE","T_CHAR_TYPE",
"T_REAL_TYPE","T_ARRAY","T_OF","S","var_declaration","var_decl_list","var_decl",
"name_list","type_dec","type","array_type_decl","x","const_value","main","stmt_list",
"stmt","write_stmt","x1","variable_list","read_stmt","y","assign_stmt","assign_expr",
"array_access","block_stmt","cond_stmt","loop_stmt","condition","boolean_expr",
"boolean_value","relational_expr","expr","unary_expr","id","num","a",""
};
#endif

static const short yyr1[] = {     0,
    51,    52,    52,    53,    53,    54,    55,    55,    56,    56,
    57,    57,    57,    57,    58,    59,    60,    60,    61,    62,
    62,    63,    63,    63,    63,    63,    63,    64,    65,    65,
    66,    66,    67,    68,    68,    69,    70,    70,    70,    70,
    70,    70,    70,    70,    71,    72,    73,    73,    74,    74,
    75,    75,    76,    76,    76,    76,    76,    77,    78,    78,
    78,    78,    78,    78,    79,    79,    79,    79,    79,    79,
    79,    79,    80,    80,    81,    81,    81,    82,    82,    83,
    83
};

static const short yyr2[] = {     0,
     6,     2,     0,     2,     1,     4,     3,     1,     1,     1,
     1,     1,     1,     1,     6,     3,     1,     2,     3,     3,
     2,     1,     1,     1,     1,     1,     1,     2,     3,     3,
     3,     1,     4,     1,     1,     3,     1,     3,     2,     3,
     3,     3,     3,     3,     4,     3,     4,     6,     4,     8,
     1,     1,     1,     2,     4,     3,     3,     1,     3,     3,
     3,     3,     3,     3,     1,     3,     1,     3,     3,     3,
     3,     3,     2,     2,     1,     1,     1,     1,     1,     1,
     1
};

static const short yydefact[] = {     0,
     0,     0,     3,     0,     0,     8,     2,     5,     0,     0,
     0,     4,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,    22,    23,    24,    25,    26,    27,     1,
     7,    11,    12,    13,    14,     0,     0,     9,    10,     0,
     0,     0,     0,    28,     0,     0,    78,    79,    75,     0,
    77,     0,    51,    53,    52,     0,    67,    65,    76,     0,
     0,    19,    21,     0,     6,     0,    75,     0,    36,    37,
    46,    34,     0,    35,    32,     0,     0,     0,    74,     0,
    58,     0,    73,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,    20,     0,     0,     0,    17,    39,     0,     0,     0,
     0,     0,     0,    33,     0,    29,    30,    73,    54,     0,
     0,    66,    47,    57,    56,    61,    62,    63,    64,    59,
    60,    68,    69,    70,    71,    72,    49,     0,    18,     0,
     0,    38,    40,    41,    42,    43,    44,    31,    55,    45,
     0,    80,    81,     0,     0,    16,    48,     0,    15,     0,
    50,     0,     0,     0
};

static const short yydefgoto[] = {   162,
     5,     7,     8,     9,    37,    38,    39,   104,   105,    11,
    22,    23,    24,    44,    77,    25,    73,    26,    69,    51,
    27,    28,    29,    52,    53,    54,    55,    56,    57,    58,
    59,   154
};

static const short yypact[] = {    10,
   -17,    23,    57,    56,    64,-32768,    56,-32768,   -10,   105,
    38,-32768,    81,   123,    69,   105,    86,    95,    -7,    -7,
   113,   114,   101,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,   106,   118,-32768,-32768,    91,
   140,   131,    77,-32768,    87,    84,-32768,-32768,     7,    87,
-32768,   152,    15,-32768,-32768,   141,-32768,-32768,-32768,   150,
   148,-32768,   105,     9,-32768,    91,   146,    91,   147,-32768,
-32768,   146,   145,-32768,   142,   149,   151,    20,    58,    84,
-32768,    20,   112,   -13,    76,   163,    20,    20,    87,    87,
    87,    87,    87,    87,    87,    87,    87,    87,    87,   163,
    87,-32768,   100,   154,   155,-32768,   165,    82,    91,    91,
    91,    91,    91,-32768,   166,-32768,-32768,    15,-32768,    54,
   156,-32768,   160,   177,-32768,   153,   153,   153,   153,   153,
   153,    58,    58,-32768,-32768,-32768,-32768,   104,-32768,   144,
     9,-32768,   165,   165,-32768,-32768,-32768,-32768,-32768,-32768,
   163,-32768,-32768,    87,   128,-32768,-32768,    11,-32768,   163,
-32768,   195,   196,-32768
};

static const short yypgoto[] = {-32768,
-32768,-32768,   191,-32768,-32768,    44,-32768,-32768,    59,-32768,
    -6,-32768,-32768,-32768,    88,-32768,-32768,-32768,   -51,   159,
   -84,-32768,-32768,   182,   -14,-32768,-32768,   -45,-32768,   -29,
   -63,-32768
};


#define	YYLAST		203


static const short yytable[] = {    79,
   106,   123,    45,     2,    85,    47,    48,    67,    46,    41,
    70,    47,    48,    49,   107,   137,   108,   -58,   103,    95,
    96,   -58,    97,    98,    99,    87,     1,    47,    48,    88,
    50,    83,    13,    14,   -58,    80,    70,   -58,    70,   139,
    81,   160,    84,   126,   127,   128,   129,   130,   131,   132,
   133,   134,   135,   136,   121,   138,   102,   143,   144,   145,
   146,   147,     3,   118,    87,   119,   157,   120,    88,    97,
    98,    99,   124,   125,     4,   161,     6,   106,    30,    70,
    70,    70,    70,    70,    95,    96,    10,    97,    98,    99,
   109,   110,   149,   111,   112,   113,    45,    75,    76,    80,
    66,    31,    78,    40,    81,    47,    48,    67,   158,    47,
    48,    67,    95,    96,   122,    97,    98,    99,    47,    48,
   142,    82,   -54,    42,    50,    15,   -54,    16,    68,    17,
    18,    19,    43,    61,    20,   152,   153,    62,    21,   -54,
    63,    64,   -54,    89,    90,    91,    92,    93,    94,    95,
    96,    72,    97,    98,    99,   109,   110,    65,   111,   112,
   113,    95,    96,    71,    97,    98,    99,    32,    33,    34,
    35,    36,    32,    33,    34,    35,   111,   112,   113,    86,
   100,    84,   101,   114,   115,    16,    75,   116,   151,   117,
   140,    88,   150,   155,   163,   164,   141,    12,   159,   156,
    74,    60,   148
};

static const short yycheck[] = {    45,
    64,    86,    10,    21,    50,    19,    20,    21,    16,    16,
    40,    19,    20,    21,    66,   100,    68,    11,    10,     9,
    10,    15,    12,    13,    14,    11,    17,    19,    20,    15,
    38,    46,    43,    44,    28,    16,    66,    31,    68,   103,
    21,    31,    36,    89,    90,    91,    92,    93,    94,    95,
    96,    97,    98,    99,    84,   101,    63,   109,   110,   111,
   112,   113,    40,    78,    11,    80,   151,    82,    15,    12,
    13,    14,    87,    88,    18,   160,    21,   141,    41,   109,
   110,   111,   112,   113,     9,    10,    23,    12,    13,    14,
     9,    10,    39,    12,    13,    14,    10,    21,    22,    16,
    10,    21,    16,    35,    21,    19,    20,    21,   154,    19,
    20,    21,     9,    10,    39,    12,    13,    14,    19,    20,
    39,    38,    11,    38,    38,    21,    15,    23,    38,    25,
    26,    27,    38,    21,    30,    32,    33,    24,    34,    28,
    40,    36,    31,     3,     4,     5,     6,     7,     8,     9,
    10,    21,    12,    13,    14,     9,    10,    40,    12,    13,
    14,     9,    10,    24,    12,    13,    14,    45,    46,    47,
    48,    49,    45,    46,    47,    48,    12,    13,    14,    28,
    31,    36,    35,    39,    43,    23,    21,    39,    29,    39,
    37,    15,    37,    50,     0,     0,    42,     7,   155,   141,
    42,    20,   115
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 31 "yacc.y"
{printf("valid input\n");return 0;;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 175 "yacc.y"


int main(int argc, char *argv[]) 
{ 
    char* filename;

    filename=argv[1];

    printf("\n");

    yyin = fopen(filename, "r");
    
    yyparse();
    
    fclose(yyin);
    return 0;
}

void yyerror(){
printf("Syntax error..\n");
}
